In [1]:
import numpy as np
import sympy as sy

# Periksa apakaha W adalah Kombinasi Linear dari V1 dan V2

In [2]:
w = np.array([-4,5,4])

v1 = np.array([2,1,0])
v2 = np.array([1,3,2])

B = sy.Matrix([[2,1,-4],[1,3,5],[0,2,4]])
B.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

c1 = 0, c2 = 0, 0 = 1 maka tidak ada solusi karena 0 = 1

# Jika T:V -> W, Transformasi Linear maka buktikan bahwa  T(-U) = -T(U)

In [3]:
u = np.array([2,3,4])
u

array([2, 3, 4])

In [4]:
T = np.array([2,5,5])

a = T*(-u)
b = -T*(u)

In [5]:
a

array([ -4, -15, -20])

In [6]:
b

array([ -4, -15, -20])

a = b , maka T(-u) dan -T(u) adalah sama.